---
title: "Apply algorithms for creating alerts"
author: "Beatriz Valcarcel"
date: "2023-01-12"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Apply algorithms for creating alerts}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r}
library(ggplot2)
library(data.table)
library(magrittr)
library(surveillance)

```

## Simulation of baseline data 

```{r}


baseline <- csalert::simulate_baseline_data(
                                    start_date = as.Date("2012-01-01"),
                                    end_date = as.Date("2019-12-31"),
                                    seasonal_pattern_n = 1,
                                    weekly_pattern_n = 2,
                                    alpha = 3, 
                                    beta = 0, 
                                    gamma_1 = 0.8, 
                                    gamma_2 = 0.6, 
                                    gamma_3 = 0.8, 
                                    gamma_4 = 0.4, 
                                    phi = 4, 
                                    shift_1 = 29)
baseline[,s:=15]

q <- ggplot(baseline, aes(x = date, y = n))
q <- q + geom_line(lwd = 1)
q <- q + facet_wrap(~s, scales = "free")
q <- q + splstyle::scale_fill_fhi(palette = "contrast")
q <- q + splstyle::theme_fhi_lines_horizontal(legend_position = "bottom")
q


# q <- ggplot(baseline, aes(wday, n, group=wday))
# q <- q + facet_wrap(~s, scales = "free")
# q <- q + geom_boxplot()
# q
# 
# q <- ggplot(baseline, aes(wday, n, group=calmonth))
# q <- q + facet_wrap(~s, scales = "free")
# q <- q + geom_boxplot()
# q

```

## Add seasonal outbreaks

```{r}
rm(baseline_with_seasonal)
baseline_with_seasonal <- csalert::simulate_seasonal_outbreak_data (baseline,
                                                           week_season_start = 40,
                                                           week_season_peak = 4,
                                                           week_season_end = 20,
                                                           n_season_outbreak = 1,
                                                           m = 140)



    q <- ggplot(baseline_with_seasonal, aes(x = date, y = n))
    q <- q + geom_line(colour = "red")
    q <- q + geom_line(data=baseline_with_seasonal, aes(x = date, y = n - seasonal_outbreak_n_rw ))
    q <- q + facet_wrap(~s, scales = "free")
    q <- q + splstyle::scale_fill_fhi(palette = "contrast")
    q <- q + splstyle::theme_fhi_lines_horizontal(legend_position = "bottom")
    q



```


## Add spikeoutbreak

```{r}

baseline_with_seasonal_spike  <- csalert::simulate_spike_outbreak_data(baseline_with_seasonal,
                                                                        n_sp_outbreak=1,
                                                                        m = 140)


  q <- ggplot(baseline_with_seasonal_spike, aes(x = date, y = n))
  q <- q + geom_line(colour = "green")
  q <- q + geom_line(data=baseline_with_seasonal, aes(x = date, y = n),colour = "red")
  q <- q + geom_line(data=baseline, aes(x = date, y = n))
  q <- q + splstyle::scale_fill_fhi(palette = "contrast")
  q <- q + splstyle::theme_fhi_lines_horizontal(legend_position = "bottom")
  q


```

## Add holiday effect  -->

```{r} 


baseline_with_seasonal_spike_holiday  <- csalert::add_holiday_effect( baseline_with_seasonal_spike, 
                                                               holiday_data= fhidata::norway_dates_holidays,
                                                               holiday_effect=0.5) 

baseline_with_seasonal_spike_holiday[,col:=seasonal_outbreak+sp_outbreak]
q <- ggplot(baseline_with_seasonal_spike_holiday , aes(x = date, y = n,colour=as.factor(col))) 
q <- q + geom_line(aes(group = 1)) 
q <- q + splstyle::scale_fill_fhi(palette = "contrast") 
q <- q + splstyle::theme_fhi_lines_horizontal(legend_position = "bottom")
q 

data <- baseline_with_seasonal_spike_holiday

``` 

## Apply Farrington Flexible algorithm for creating alerts  -->

```{r}
out_farringtonflex <- farrington_algorithm_create_alerts(baseline_with_seasonal_spike_holiday,
                                    method = "farrington_flexible",
                                    p = 10,
                                    b = 4,
                                    freq = 365,
                                    w = 3,
                                    weeks_excluded_n = 23,
                                    offset = F,
                                    reweights = 1,
                                    remove.highcounts = 0,
                                    is_day = T,
                                    s = 2.58
                                    )

``` 



## Apply Quasipoisson Algorithm for creating alerts (sykdomspulsen algorithm)  -->

```{r}
out_sykdomspulsen <- farrington_algorithm_create_alerts(baseline_with_seasonal_spike_holiday,
                                                  b = 5,
                                                  offset = F,
                                                  reweights = 1,
                                                  remove.highcounts = 0,
                                                  is_day = T,
                                                  s = 2.58 )

``` 

